import 'package:pixply/Games/Snakes.dart';
import 'package:pixply/Games/aduhuli.dart';
import 'package:pixply/Games/agon.dart';
import 'package:pixply/Games/aseb.dart';
import 'package:pixply/Games/ashtachamma.dart';
import 'package:pixply/Games/crossgrid.dart';
import 'package:pixply/Games/dablotprejjesne.dart';
import 'package:pixply/Games/dama.dart';
import 'package:pixply/Games/fanaron.dart';
import 'package:pixply/Games/fivefieldkono.dart';
import 'package:pixply/Games/adugo.dart';
import 'package:pixply/Games/lenchoa.dart';
import 'package:pixply/Games/leopardandcow.dart';
import 'package:pixply/Games/manmoon.dart';
import 'package:pixply/Games/pentalpha.dart';
import 'package:pixply/Games/pretwa.dart';
import 'package:pixply/Games/rimau.dart';
import 'package:pixply/Games/sahkku.dart';
import 'package:pixply/Games/sixmens.dart';
import 'package:pixply/Games/backgammon.dart';
import 'package:pixply/Games/chess.dart';
import 'package:pixply/Games/ludo.dart';
import 'package:pixply/Games/patolli.dart';
import 'package:pixply/Games/ninemens.dart';
import 'package:led_ble_lib/led_ble_lib.dart';
import 'package:pixply/Games/tapatan.dart';
import 'package:pixply/Games/threemenmorris.dart';
import 'package:pixply/Games/tonkin.dart';
import 'package:pixply/Games/watermelonchess.dart';
import 'package:pixply/Games/xo.dart';
import 'package:pixply/Games/othello.dart';
import 'package:pixply/Games/alquerque.dart';
import 'package:pixply/Games/asalto.dart';
import 'package:pixply/Games/achi.dart';
import 'package:pixply/Games/baghchal.dart';
import 'package:pixply/Games/catchthehare.dart';
import 'package:pixply/Games/checkers.dart';
import 'package:pixply/Games/choko.dart';
import 'package:pixply/Games/foxandgeese.dart';
import 'package:pixply/Games/yote.dart';
import 'package:pixply/Games/dara.dart';
import 'package:pixply/Games/felli.dart';
import 'package:pixply/Games/gomoku.dart';
import 'package:pixply/Games/patgonu.dart';
import 'package:pixply/Games/linesofaction.dart';
import 'package:pixply/Games/mutorere.dart';
import 'package:pixply/Games/neutron.dart';
import 'package:pixply/Games/ordo.dart';
import 'package:pixply/Games/pahtum.dart';
import 'package:pixply/Games/duplodraughts.dart';
import 'package:pixply/Games/halma.dart';
import 'package:pixply/Games/puluc.dart';
import 'package:pixply/Games/seega.dart';
import 'package:pixply/Games/hnefatafl.dart';
import 'package:pixply/Games/kharbaga.dart';
import 'package:pixply/Games/konane.dart';
import 'package:pixply/Games/madelinette.dart';
import 'package:pixply/Games/picaria.dart';
import 'package:pixply/Games/queah.dart';
import 'package:pixply/Games/surakarta.dart';
import 'package:pixply/Games/brandubh.dart';
import 'package:pixply/Games/go.dart';
import 'package:pixply/Games/hyenachase.dart';
// import 'package:pixply/Games/zohnahl.dart';
import 'package:pixply/Games/pentegerammi.dart';
import 'package:pixply/Games/awithlaknannai.dart';
import 'package:pixply/Games/ur.dart';
import 'package:pixply/Games/latrunculi.dart';
import 'package:pixply/Games/rota.dart';
import 'package:pixply/Games/tab.dart';
import 'package:pixply/Games/morabaraba.dart';


List<Map<String, dynamic>> buildGameList(
  LedBluetooth bluetooth,
  bool isConnected,
) {
  return [
    {
      'id': 'Ludo',
      'name': 'Ludo',
      'image': 'assets/ludo.png',
      'players': '2-4',
      'country': 'India',
      'difficulty': 'Medium',
      'mindEffect': ['Focus', 'Risk'],
      'ageRange': {'min': 5, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Race', 'Luck/Chance'],
      'page': LudoScreen(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Ludo-1.png',
        gameTitle: 'Ludo',
        gameId: 'Ludo',
      ),
    },
    {
      'id': 'Chess',
      'name': 'Chess',
      'image': 'assets/chess.png',
      'players': '2',
      'country': 'India',
      'difficulty': 'Hard',
      'mindEffect': ['Logic', 'Focus', 'Memory'],
      'ageRange': {'min': 10, 'max': 99},
      'playTimeCategory': '30–60 min',
      'category': ['Strategy', 'Tactical', 'Abstract'],
      'page': Chess(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/chess-1.png',
        gameTitle: 'Chess',
        gameId: 'Chess',
      ),
    },
    {
      'id': 'Backgammon',
      'name': 'Backgammon',
      'image': 'assets/backgamon.png',
      'players': '2',
      'country': 'Persia',
      'difficulty': 'Medium',
      'mindEffect': ['Logic', 'Risk', 'Math'],
      'ageRange': {'min': 6, 'max': 99},
      'category': ['Strategy', 'Luck/Chance', 'Race'],
      'playTimeCategory': '30–60 min',
      'page': Backgammon(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Backgammon-1.png',
        gameTitle: 'Backgammon',
        gameId: 'Backgammon',
      ),
    },
    {
      'id': 'Nine Men’s Morris',
      'name': 'Nine Men’s Morris',
      'image': 'assets/Nine Mens Morris.png',
      'players': '2',
      'country': 'Rome',
      'difficulty': 'Medium',
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 7, 'max': 99},
      'category': ['Strategy', 'Abstract', 'Area Control'],
      'playTimeCategory': '30–60 min',
      'page': NineMens(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Nine Mens Morris-1.png',
        gameTitle: 'Nine Men’s Morris',
        gameId: 'Nine Men’s Morris',
      ),
    },
    {
      'id': 'Six Men’s Morris',
      'name': 'Six Men’s Morris',
      'image': 'assets/sixmens.png',
      'players': '2',
      'country': 'Europe',
      'difficulty': ['Easy', 'Medium'],
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Strategy', 'Abstract', 'Area Control'],
      'page': SixMensScreen(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Sixmens-1.png',
        gameTitle: 'Six Men’s Morris',
        gameId: 'Six Men’s Morris',
      ),
    },
    {
      'id': 'Xo',
      'name': 'Xo',
      'image': 'assets/Xo.png',
      'players': '2',
      'country': 'Egypt',
      'difficulty': 'Easy',
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 5, 'max': 99},
      'playTimeCategory': 'Under 15 min',
      'category': ['Abstract', 'Strategy'],
      'page': Xo(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/xo-1.png',
        gameTitle: 'Xo',
        gameId: 'Xo',
      ),
    },
    {
      'id': 'Reversi',
      'name': 'Reversi',
      'image': 'assets/Othello.png',
      'players': '2',
      'country': 'Japan',
      'difficulty': ['Hard', 'Medium'],
      'mindEffect': ['Logic', 'Memory'],
      'ageRange': {'min': 10, 'max': 99},
      'playTimeCategory': '60+ min',
      'category': ['Abstract', 'Tactical', 'Strategy', 'Area Control'],
      'page': Othello(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/othello-1.png',
        gameTitle: 'Reversi',
        gameId: 'Reversi',
      ),
    },
    {
      'id': 'Adugo',
      'name': 'Adugo',
      'image': 'assets/Adugo.png',
      'players': '2',
      'country': 'Brazil',
      'difficulty': 'Medium',
      'mindEffect': ['Logic', 'Social'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Asymmetrical', 'Strategy', 'Tactical'],
      'page': Adugo(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Adugo-1.png',
        gameTitle: 'Adugo',
        gameId: 'Adugo',
      ),
    },
    {
      'id': 'Alquerque',
      'name': 'Alquerque',
      'image': 'assets/Alquerque.png',
      'players': '2',
      'country': 'Spain',
      'difficulty': 'Medium',
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Tactical', 'Strategy', 'Abstract'],
      'page': Alquerque(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Alquerque-1.png',
        gameTitle: 'Alquerque',
        gameId: 'Alquerque',
      ),
    },
    {
      'id': 'Asalto',
      'name': 'Asalto',
      'image': 'assets/Asalto.png',
      'players': '2',
      'country': 'Europe',
      'difficulty': 'Medium',
      'mindEffect': ['Logic', 'Social'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '30–60 min',
      'category': ['Strategy', 'Asymmetrical', 'Tactical'],
      'page': Asalto(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Asalto-1.png',
        gameTitle: 'Asalto',
        gameId: 'Asalto',
      ),
    },
    {
      'id': 'Achi',
      'name': 'Achi',
      'image': 'assets/Achi.png',
      'players': '2',
      'country': 'Ghana',
      'difficulty': ['Easy', 'Medium'],
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 10, 'max': 99},
      'playTimeCategory': 'Under 15 min',
      'category': ['Abstract', 'Strategy'],
      'page': Achi(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Achi-1.png',
        gameTitle: 'Achi',
        gameId: 'Achi',
      ),
    },
    {
      'id': 'Bagh chal',
      'name': 'Bagh chal',
      'image': 'assets/Bagh chal.png',
      'players': '2',
      'country': 'Nepal',
      'difficulty': ['Hard', 'Medium'],
      'mindEffect': ['Logic', 'Creativity'],
      'ageRange': {'min': 8, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Strategy', 'Tactical', 'Asymmetrical'],
      'page': Baghchal(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Baghchal-1.png',
        gameTitle: 'Bagh chal',
        gameId: 'Bagh chal',
      ),
    },
    {
      'id': 'Catch the hare',
      'name': 'Catch the hare',
      'image': 'assets/Catch the hare.png',
      'players': '2',
      'country': 'Europe',
      'mindEffect': ['Focus', 'Logic'],
      'difficulty': 'Medium',
      'ageRange': {'min': 8, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Strategy', 'Asymmetrical', 'Tactical'],
      'page': Catchthehare(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Catchthehare-1.png',
        gameTitle: 'Catch the hare',
        gameId: 'Catch the hare',
      ),
    },
    {
      'id': 'Checkers',
      'name': 'Checkers',
      'image': 'assets/Checkers.png',
      'players': '2',
      'country': 'France',
      'difficulty': 'Medium',
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 6, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Strategy', 'Tactical', 'Abstract'],
      'page': Checkers(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Checkers-1.png',
        gameTitle: 'Checkers',
        gameId: 'Checkers',
      ),
    },
    {
      'id': 'Choko',
      'name': 'Choko',
      'image': 'assets/Choko.png',
      'players': '2',
      'country': 'Africa',
      'difficulty': 'Medium',
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 6, 'max': 99},
      'playTimeCategory': 'Under 15 min',
      'category': ['Abstract', 'Tactical', 'Strategy'],
      'page': Choko(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/choko-1.png',
        gameTitle: 'Choko',
        gameId: 'Choko',
      ),
    },
    {
      'id': 'Five field kono',
      'name': 'Five field kono',
      'image': 'assets/Fivefieldkono.png',
      'players': '2',
      'country': 'Korea',
      'difficulty': ['Medium', 'Easy'],
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Abstract', 'Strategy'],
      'page': Fivefieldkono(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Five field kono-1.png',
        gameTitle: 'Five field kono',
        gameId: 'Five field kono',
      ),
    },
    {
      'id': 'Fox and geese',
      'name': 'Fox and geese',
      'image': 'assets/Fox and geese.png',
      'players': '2',
      'country': 'Scandinavia',
      'difficulty': 'Medium',
      'mindEffect': ['Logic', 'Social'],
      'ageRange': {'min': 8, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Asymmetrical', 'Tactical', 'Strategy'],
      'page': Fox(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Fox-1.png',
        gameTitle: 'Fox and geese',
        gameId: 'Fox and geese',
      ),
    },
    {
      'id': 'Yote',
      'name': 'Yote',
      'image': 'assets/Yote.png',
      'players': '2',
      'country': 'Africa',
      'difficulty': 'Medium',
      'mindEffect': ['Logic', 'Creativity'],
      'ageRange': {'min': 10, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Abstract', 'Tactical', 'Strategy'],
      'page': Yote(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Yote-1.png',
        gameTitle: 'Yote',
        gameId: 'Yote',
      ),
    },
    {
      'id': 'Fanorona',
      'name': 'Fanorona',
      'image': 'assets/Fanaron.png',
      'players': '2',
      'country': 'Madagascar',
      'difficulty': 'Hard',
      'mindEffect': ['Logic', 'Memory'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '30–60 min',
      'category': ['Abstract', 'Strategy', 'Tactical'],
      'page': Fanaron(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Fanaron-1.png',
        gameTitle: 'Fanorona',
        gameId: 'Fanorona',
      ),
    },
    {
      'id': 'Felli',
      'name': 'Felli',
      'image': 'assets/Felli.png',
      'players': '2',
      'country': 'Morocco',
      'difficulty': ['Easy', 'Medium'],
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': 'Under 15 min',
      'category': ['Abstract', 'Strategy'],
      'page': Felli(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Felli-1.png',
        gameTitle: 'Felli',
        gameId: 'Felli',
      ),
    },
    {
      'id': 'Gomoku',
      'name': 'Gomoku',
      'image': 'assets/Gomoko.png',
      'players': '2',
      'country': 'Japan',
      'difficulty': ['Hard', 'Medium'],
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 10, 'max': 99},
      'playTimeCategory': '60+ min',
      'category': ['Abstract', 'Strategy'],
      'page': Gomoku(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Gomoko-1.png',
        gameTitle: 'Gomoku',
        gameId: 'Gomoku',
      ),
    },
    {
      'id': 'Pat Gonu',
      'name': 'Pat Gonu',
      'image': 'assets/patgonu.png',
      'players': '2',
      'country': 'Korea',
      'difficulty': ['Easy', 'Medium'],
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 5, 'max': 99},
      'playTimeCategory': 'Under 15 min',
      'category': ['Abstract', 'Strategy'],
      'page': PatGonu(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/patgonu-1.png',
        gameTitle: 'Pat Gonu',
        gameId: 'Pat Gonu',
      ),
    },
    {
      'id': 'Lines Clash',
      'name': 'Lines Clash',
      'image': 'assets/Loa.png',
      'players': '2',
      'country': 'United States',
      'difficulty': 'Hard',
      'mindEffect': ['Logic', 'Memory'],
      'ageRange': {'min': 10, 'max': 99},
      'playTimeCategory': '30–60 min',
      'category': ['Strategy', 'Tactical', 'Abstract'],
      'page': LOA(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/LoA-1.png',
        gameTitle: 'Lines Clash',
        gameId: 'Lines Clash',
      ),
    },
    {
      'id': 'Dara',
      'name': 'Dara',
      'image': 'assets/Dara.png',
      'players': '2',
      'country': 'Africa',
      'difficulty': 'Medium',
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 8, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Strategy', 'Tactical', 'Abstract'],
      'page': Dara(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/dara-1.png',
        gameTitle: 'Dara',
        gameId: 'Dara',
      ),
    },
    {
      'id': 'Mu Torere',
      'name': 'Mu Torere',
      'image': 'assets/muturere-1.png',
      'players': '2',
      'country': 'New Zealand',
      'difficulty': ['Easy', 'Medium'],
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 6, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Strategy', 'Abstract'],
      'page': MuTorere(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/mutorere.png',
        gameTitle: 'Mu Torere',
        gameId: 'Mu Torere',
      ),
    },
    {
      'id': 'Gravity Move',
      'name': 'Gravity Move',
      'image': 'assets/neutrn-1.png',
      'players': '2',
      'country': 'United States',
      'difficulty': ['Hard', 'Medium'],
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 10, 'max': 99},
      'playTimeCategory': 'Under 15 min',
      'category': ['Abstract', 'Strategy', 'Tactical'],
      'page': Neutron(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/neutrn.png',
        gameTitle: 'Gravity Move',
        gameId: 'Gravity Move',
      ),
    },
    {
      'id': 'Order Clash',
      'name': 'Order Clash',
      'image': 'assets/ordo.png',
      'players': '2',
      'country': 'Finland',
      'difficulty': ['Hard', 'Medium'],
      'mindEffect': ['Logic', 'Memory'],
      'ageRange': {'min': 8, 'max': 99},
      'playTimeCategory': '30–60 min',
      'category': ['Abstract', 'Strategy', 'Tactical'],
      'page': Ordo(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/ordo-1.png',
        gameTitle: 'Order Clash',
        gameId: 'Order Clash',
      ),
    },
    {
      'id': 'Pah tum ',
      'name': 'Pah tum ',
      'image': 'assets/Pah tum.png',
      'players': '2',
      'country': 'Thailand',
      'difficulty': ['Easy', 'Medium'],
      'mindEffect': ['Logic', 'Math'],
      'ageRange': {'min': 10, 'max': 99},
      'playTimeCategory': '30–60 min',
      'category': ['Strategy', 'Abstract'],
      'page': Pahtum(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Pah tum-1.png',
        gameTitle: 'Pah tum ',
        gameId: 'Pah tum',
      ),
    },
    {
      'id': 'Twin Draughts',
      'name': 'Twin Draughts',
      'image': 'assets/Duplo Draughts-1.png',
      'players': '2',
      'country': 'France',
      'difficulty': 'Easy',
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': 'Under 15 min',
      'category': ['Abstract', 'Strategy'],
      'page': DuploDraughts(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Duplo Draughts.png',
        gameTitle: 'Twin Draughts',
        gameId: 'Twin Draughts',
      ),
    },
    {
      'id': 'Halma',
      'name': 'Halma',
      'image': 'assets/Halma.png',
      'players': '2-4',
      'country': 'United States',
      'difficulty': 'Medium',
      'mindEffect': ['Logic', 'Creativity'],
      'ageRange': {'min': 10, 'max': 99},
      'playTimeCategory': '30–60 min',
      'category': ['Tactical', 'Abstract', 'Strategy'],
      'page': Halma(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Halma-1.png',
        gameTitle: 'Halma',
        gameId: 'Halma',
      ),
    },
    {
      'id': 'Puluc',
      'name': 'Puluc',
      'image': 'assets/Puluc.png',
      'players': '2',
      'country': 'Guatemala',
      'difficulty': 'Medium',
      'mindEffect': ['Math', 'Risk'],
      'ageRange': {'min': 6, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Race', 'Strategy', 'Luck/Chance'],
      'page': Puluc(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Puluc-1.png',
        gameTitle: 'Puluc',
        gameId: 'Puluc',
      ),
    },
    {
      'id': 'Seega',
      'name': 'Seega',
      'image': 'assets/Seega.png',
      'players': '2',
      'country': 'Egypt',
      'difficulty': 'Medium',
      'mindEffect': ['Logic', 'Math'],
      'ageRange': {'min': 5, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Tactical', 'Strategy', 'Abstract'],
      'page': Seega(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Seega-1.png',
        gameTitle: 'Seega',
        gameId: 'Seega',
      ),
    },
    {
      'id': 'Hnefatafl',
      'name': 'Hnefatafl',
      'image': 'assets/Hnefatafl.png',
      'players': '2',
      'country': 'Scandinavia',
      'difficulty': 'Professional',
      'mindEffect': ['Logic', 'Social'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '30–60 min',
      'category': ['Strategy', 'Asymmetrical', 'Tactical'],
      'page': Hnefatafl(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Hnefatafl-1.png',
        gameTitle: 'Hnefatafl',
        gameId: 'Hnefatafl',
      ),
    },
    {
      'id': 'Kharbaga',
      'name': 'Kharbaga',
      'image': 'assets/Kharbaga.png',
      'players': '2',
      'country': 'Africa',
      'difficulty': 'Medium',
      'mindEffect': ['Logic', 'Math'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Strategy', 'Abstract', 'Tactical'],
      'page': Kharbaga(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Kharbaga-1.png',
        gameTitle: 'Kharbaga',
        gameId: 'Kharbaga',
      ),
    },
    {
      'id': 'Konane',
      'name': 'Konane',
      'image': 'assets/Konane.png',
      'players': '2',
      'country': 'Hawaii',
      'difficulty': 'Medium',
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 6, 'max': 99},
      'playTimeCategory': 'Under 15 min',
      'category': ['Strategy', 'Abstract', 'Tactical'],
      'page': Konane(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Konane-1.png',
        gameTitle: 'Konane',
        gameId: 'Konane',
      ),
    },
    {
      'id': 'Madelinette',
      'name': 'Madelinette',
      'image': 'assets/Madelinette.png',
      'players': '2',
      'country': 'France',
      'difficulty': 'Medium',
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Abstract', 'Strategy', 'Tactical'],
      'page': Madelinette(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Madelinette-1.png',
        gameTitle: 'Madelinette',
        gameId: 'Madelinette',
      ),
    },
    {
      'id': 'Picaria',
      'name': 'Picaria',
      'image': 'assets/Picaria.png',
      'players': '2',
      'country': 'United States',
      'difficulty': ['Easy', 'Medium'],
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': 'Under 15 min',
      'category': ['Abstract', 'Strategy'],
      'page': Picaria(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Picaria-1.png',
        gameTitle: 'Picaria',
        gameId: 'Picaria',
      ),
    },
    {
      'id': 'Queah',
      'name': 'Queah',
      'image': 'assets/Queah.png',
      'players': '2',
      'country': 'Africa',
      'difficulty': ['Easy', 'Medium'],
      'mindEffect': ['Logic', 'Math'],
      'ageRange': {'min': 6, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Abstract', 'Strategy'],
      'page': Queah(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Queah-1.png',
        gameTitle: 'Queah',
        gameId: 'Queah',
      ),
    },
    {
      'id': 'Surakarta',
      'name': 'Surakarta',
      'image': 'assets/Surakarta.png',
      'players': '2',
      'country': 'Indonesia',
      'difficulty': 'Medium',
      'mindEffect': ['Logic', 'Creativity'],
      'ageRange': {'min': 8, 'max': 99},
      'playTimeCategory': '30–60 min',
      'category': ['Abstract', 'Strategy', 'Tactical'],
      'page': Surakarta(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Surakarta-1.png',
        gameTitle: 'Surakarta',
        gameId: 'Surakarta',
      ),
    },
    {
      'id': 'Brandubh',
      'name': 'Brandubh',
      'image': 'assets/Brandubh.png',
      'players': '2',
      'country': 'Ireland',
      'difficulty': 'Medium',
      'mindEffect': ['Logic', 'Social'],
      'ageRange': {'min': 8, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Strategy', 'Tactical', 'Asymmetrical'],
      'page': Brandubh(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Brandubh-1.png',
        gameTitle: 'Brandubh',
        gameId: 'Brandubh',
      ),
    },
    {
      'id': 'Go',
      'name': 'Go',
      'image': 'assets/Go.png',
      'players': '2',
      'country': 'China',
      'difficulty': 'Hard',
      'mindEffect': ['Logic', 'Memory'],
      'ageRange': {'min': 10, 'max': 99},
      'playTimeCategory': '60+ min',
      'category': ['Strategy', 'Abstract', 'Area Control'],
      'page': Go(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Go-1.png',
        gameTitle: 'Go',
        gameId: 'Go',
      ),
    },
    {
      'id': 'Hyenachase',
      'name': 'Hyenachase',
      'image': 'assets/Hyenachase.png',
      'players': '2-4',
      'country': 'Africa',
      'difficulty': ['Easy', 'Medium'],
      'mindEffect': ['Focus', 'Risk'],
      'ageRange': {'min': 4, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Race', 'Luck/Chance', 'Strategy'],
      'page': Hyenachase(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Hyenachase-1.png',
        gameTitle: 'Hyenachase',
        gameId: 'Hyenachase',
      ),
    },
    // {
    //   'id': 'Zohnahl',
    //   'name': 'Zohnahl',
    //   'image': 'assets/Zohnahl.png',
    //   'players': '2',
    //   'country': 'United States',
    //   'difficulty': 'Medium',
    //   'mindEffect': ['Logic', 'Social'],
    //   'ageRange': {'min': 5, 'max': 99},
    //   'playTimeCategory': '15–30 min',
    //   'category': ['Tactical', 'Abstract', 'Strategy'],
    //   'page': Zohnahl(
    //     bluetooth: bluetooth,
    //     isConnected: isConnected,
    //     gameImage: 'assets/Zohnahl-1.png',
    //     gameTitle: 'Zohnahl',
    //     gameId: 'Zohnahl',
    //   ),
    // },
    {
      'id': 'Patolli',
      'name': 'Patolli',
      'image': 'assets/Patolli.png',
      'players': '2',
      'country': 'Mesoamerica',
      'difficulty': 'Medium',
      'mindEffect': ['Math', 'Risk'],
      'ageRange': {'min': 6, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Luck/Chance', 'Race', 'Strategy'],
      'page': Patolli(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Patolli-1.png',
        gameTitle: 'Patolli',
        gameId: 'Patolli',
      ),
    },
    {
      'id': 'Pente Gerammi',
      'name': 'Pente Gerammi',
      'image': 'assets/PenteGerammi.png',
      'players': '2',
      'country': 'Greece',
      'difficulty': 'Medium',
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 10, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Abstract', 'Strategy'],
      'page': PenteGerammi(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/PenteGerammi-1.png',
        gameTitle: 'Pente Gerammi',
        gameId: 'Pente Gerammi',
      ),
    },
    {
      'id': 'Awithlaknannai',
      'name': 'Awithlaknannai',
      'image': 'assets/Awithlaknannai.png',
      'players': '2',
      'country': 'Mexico',
      'difficulty': ['Hard', 'Medium'],
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '30–60 min',
      'category': ['Strategy', 'Tactical', 'Abstract'],
      'page': Awithlaknannai(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Awithlaknannai-1.png',
        gameTitle: 'Awithlaknannai',
        gameId: 'Awithlaknannai',
      ),
    },
    {
      'id': 'UR',
      'name': 'UR',
      'image': 'assets/UR.png',
      'players': '2',
      'country': 'Mesopotamia',
      'difficulty': 'Medium',
      'mindEffect': ['Math', 'Risk'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Race', 'Luck/Chance', 'Strategy'],
      'page': UR(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/UR-1.png',
        gameTitle: 'UR',
        gameId: 'UR',
      ),
    },
    {
      'id': 'Latrunculi',
      'name': 'Latrunculi',
      'image': 'assets/Latrunculi.png',
      'players': '2',
      'country': 'Rome',
      'difficulty': ['Hard', 'Medium'],
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 10, 'max': 99},
      'playTimeCategory': '30–60 min',
      'category': ['Tactical', 'Strategy', 'Abstract'],
      'page': Latrunculi(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Latrunculi-1.png',
        gameTitle: 'Latrunculi',
        gameId: 'Latrunculi',
      ),
    },
    {
      'id': 'Rota',
      'name': 'Rota',
      'image': 'assets/Rota.png',
      'players': '2',
      'country': 'Rome',
      'difficulty': ['Easy', 'Medium'],
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 8, 'max': 99},
      'playTimeCategory': 'Under 15 min',
      'category': ['Abstract', 'Strategy'],
      'page': Rota(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Rota-1.png',
        gameTitle: 'Rota',
        gameId: 'Rota',
      ),
    },
    {
      'id': 'Table of the four season',
      'name': 'Table of the four season',
      'image': 'assets/Tableofthefourseason-1.png',
      'players': '4',
      'country': 'Spain',
      'difficulty': 'Medium',
      'mindEffect': ['Focus', 'Risk'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Strategy', 'Abstract'],
      'page': TablePage(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Tableofthefourseason.png',
        gameTitle: 'Table of the four season',
        gameId: 'Table of the four season',
      ),
    },
    {
      'id': 'Morabaraba',
      'name': 'Morabaraba',
      'image': 'assets/Morabaraba.png',
      'players': '2',
      'country': 'South Africa',
      'difficulty': 'Medium',
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Strategy', 'Abstract', 'Tactical', 'Area Control'],
      'page': Morabaraba(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Morabaraba-1.png',
        gameTitle: 'Morabaraba',
        gameId: 'Morabaraba',
      ),
    },
    {
      'id': 'Len choa',
      'name': 'Len choa',
      'image': 'assets/LenChoa.png',
      'players': '2',
      'country': 'Thailand',
      'difficulty': ['Easy', 'Medium'],
      'mindEffect': ['Creativity', 'Logic'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': [
        'Strategy',
        'Asymmetrical',
        'Deduction/MindGames',
        'Area Control'
      ],
      'page': LenChoa(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/LenChoa-1.png',
        gameTitle: 'Len choa',
        gameId: 'Len choa',
      ),
    },
    {
      'id': 'Leopard and cow',
      'name': 'Leopard and cow',
      'image': 'assets/Leopardandcow.png',
      'players': '2',
      'country': 'India',
      'difficulty': ['Easy', 'Medium'],
      'mindEffect': ['Social', 'Logic'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Strategy', 'Asymmetrical', 'Tactical'],
      'page': LeopardCow(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Leopardandcow-1.png',
        gameTitle: 'Leopard and cow',
        gameId: 'Leopard and cow',
      ),
    },
    {
      'id': 'Tapatan',
      'name': 'Tapatan',
      'image': 'assets/Tapatan.png',
      'players': '2',
      'country': 'Philippines',
      'difficulty': 'Easy',
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Strategy', 'Abstract'],
      'page': Tapatan(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Tapatan-1.png',
        gameTitle: 'Tapatan',
        gameId: 'Tapatan',
      ),
    },
    {
      'id': 'Pretwa',
      'name': 'Pretwa',
      'image': 'assets/Pretwa.png',
      'players': '2',
      'country': 'India',
      'difficulty': 'Medium',
      'mindEffect': ['Creativity', 'Logic'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Strategy', 'Abstract', 'Tactical'],
      'page': Pretwa(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Pretwa-1.png',
        gameTitle: 'Pretwa',
        gameId: 'Pretwa',
      ),
    },
    {
      'id': 'Cross Grid',
      'name': 'Cross Grid',
      'image': 'assets/Cross Grid.png',
      'players': '1',
      'country': 'Europe',
      'difficulty': 'Medium',
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Strategy', 'Abstract', 'Tactical'],
      'page': CrossGrid(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Cross Grid-1.png',
        gameTitle: 'Cross Grid',
        gameId: 'Cross Grid',
      ),
    },
    {
      'id': 'Aseb',
      'name': 'Aseb',
      'image': 'assets/Aseb.png',
      'players': '2',
      'country': 'Egypt',
      'difficulty': ['Easy', 'Medium'],
      'mindEffect': ['Focus', 'Logic'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Race', 'Luck/Chance'],
      'page': Aseb(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Aseb-1.png',
        gameTitle: 'Aseb',
        gameId: 'Aseb',
      ),
    },
    {
      'id': 'Pentalpha',
      'name': 'Pentalpha',
      'image': 'assets/Pentalpha.png',
      'players': '1',
      'country': 'Greece',
      'difficulty': 'Medium',
      'mindEffect': ['Creativity', 'Logic'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Abstract', 'Strategy', 'Tactical'],
      'page': Pentalpha(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Pentalpha-1.png',
        gameTitle: 'Pentalpha',
        gameId: 'Pentalpha',
      ),
    },
    {
      'id': 'Snakes and ladders',
      'name': 'Snakes and ladders',
      'image': 'assets/Snakes and ladders.png',
      'players': '2-4',
      'country': 'India',
      'difficulty': 'Easy',
      'mindEffect': ['Risk', 'Focus'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Luck/Chance', 'Race'],
      'page': SnakesLadders(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Snakes and ladders-1.png',
        gameTitle: 'Snakes and ladders',
        gameId: 'Snakes and ladders',
      ),
    },
    {
      'id': 'Agon',
      'name': 'Agon',
      'image': 'assets/Agon.png',
      'players': '2',
      'country': 'France',
      'difficulty': 'Medium',
      'mindEffect': ['Logic', 'Memory'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Abstract', 'Strategy', 'Tactical'],
      'page': Agon(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Agon-1.png',
        gameTitle: 'Agon',
        gameId: 'Agon',
      ),
    },
    {
      'id': 'Watermelon chess',
      'name': 'Watermelon chess',
      'image': 'assets/Watermelon chess.png',
      'players': '2',
      'country': 'China',
      'difficulty': 'Medium',
      'mindEffect': ['Logic', 'Focus'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Abstract', 'Strategy', 'Tactical'],
      'page': WatermelonChess(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Watermelon chess-1.png',
        gameTitle: 'Watermelon chess',
        gameId: 'Watermelon chess',
      ),
    },
    {
      'id': 'The Man in the Moon',
      'name': 'The Man in the Moon',
      'image': 'assets/The Man in the Moon.png',
      'players': '2',
      'country': 'England',
      'difficulty': 'Medium',
      'mindEffect': ['Logic', 'Focus'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Abstract', 'Strategy', 'Tactical', 'Area Control'],
      'page': ManMoon(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/The Man in the Moon-1.png',
        gameTitle: 'The Man in the Moon',
        gameId: 'The Man in the Moon',
      ),
    },
    {
      'id': 'Sahkku',
      'name': 'Sahkku',
      'image': 'assets/Sahkku.png',
      'players': '2',
      'country': 'Scandinavia',
      'difficulty': 'Medium',
      'mindEffect': ['Logic', 'Focus'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Race', 'Strategy', 'Luck/Chance'],
      'page': Sahkku(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Sahkku-1.png',
        gameTitle: 'Sahkku',
        gameId: 'Sahkku',
      ),
    },
    {
      'id': 'Dama',
      'name': 'Dama',
      'image': 'assets/Dama.png',
      'players': '2',
      'country': 'Turkey',
      'difficulty': 'Medium',
      'mindEffect': ['Logic', 'Focus'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Abstract', 'Strategy', 'Tactical'],
      'page': Dama(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Dama-1.png',
        gameTitle: 'Dama',
        gameId: 'Dama',
      ),
    },
    {
      'id': 'Rimau',
      'name': 'Rimau',
      'image': 'assets/Rimau.png',
      'players': '2',
      'country': 'Malaysia',
      'difficulty': 'Medium',
      'mindEffect': ['Logic', 'Social'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Asymmetrical', 'Strategy', 'Tactical'],
      'page': Rimau(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Rimau-1.png',
        gameTitle: 'Rimau',
        gameId: 'Rimau',
      ),
    },
    {
      'id': 'Three Men’s Morris',
      'name': 'Three Men’s Morris',
      'image': 'assets/Three Men’s Morris.png',
      'players': '2',
      'country': 'Egypt',
      'difficulty': 'Easy',
      'mindEffect': ['Logic', 'Focus'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Abstract', 'Strategy'],
      'page': ThreeMensMorris(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Three Men’s Morris-1.png',
        gameTitle: 'Three Men’s Morris',
        gameId: 'Three Men’s Morris',
      ),
    },
    {
      'id': 'Ashta Chamma',
      'name': 'Ashta Chamma',
      'image': 'assets/Ashta Chamma.png',
      'players': '2-4',
      'country': 'India',
      'difficulty': ['Easy', 'Medium'],
      'mindEffect': ['Risk', 'Focus'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Race', 'Strategy', 'Luck/Chance'],
      'page': AshtaChamma(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/AshtaChamma-1.png',
        gameTitle: 'Ashta Chamma',
        gameId: 'Ashta Chamma',
      ),
    },
    {
      'id': 'Dablot Prejjesne',
      'name': 'Dablot Prejjesne',
      'image': 'assets/Dablot Prejjesne.png',
      'players': '2',
      'country': 'Scandinavia',
      'difficulty': ['Hard', 'Medium'],
      'mindEffect': ['Logic', 'Social'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Tactical', 'Strategy', 'Asymmetrical'],
      'page': DablotPrejjesne(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Dablot Prejjesne-1.png',
        gameTitle: 'Dablot Prejjesne',
        gameId: 'Dablot Prejjesne',
      ),
    },
    {
      'id': 'Adu huli',
      'name': 'Adu huli',
      'image': 'assets/Adu huli.png',
      'players': '2',
      'country': 'India',
      'difficulty': 'Medium',
      'mindEffect': ['Logic', 'Social'],
      'ageRange': {'min': 7, 'max': 99},
      'playTimeCategory': '15–30 min',
      'category': ['Tactical', 'Strategy', 'Asymmetrical'],
      'page': AduHuli(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Adu huli-1.png',
        gameTitle: 'Adu huli',
        gameId: 'Adu huli',
      ),
    },
      {
      'id': 'Tonkin',
      'name': 'Tonkin',
      'image': 'assets/Tonkin-1.png',
      'players': '2',
      'country': 'France',
      'difficulty': 'Professional',
      'mindEffect': ['Logic', 'Focus'],
      'ageRange': {'min': 14, 'max': 99},
      'playTimeCategory': '60+ min',
      'category': [ 'Strategy', 'Area Control'],
      'page': Tonkin(
        bluetooth: bluetooth,
        isConnected: isConnected,
        gameImage: 'assets/Tonkin.png',
        gameTitle: 'Tonkin',
        gameId: 'Tonkin',
      ),
    },
  ];
}
